### ISSUE TITLE
pomatez: power usage

### ISSUE THREAD

**Issue by pared** [roldanjr/pomatez#174] opened 2021-07-20 09:38 UTC
version: 1.1.0, mac

I've been using pomatez for a few months now, on mac, and the system battery utility has been pointing to pomatez as one of the main battery users, competing with Safari and PyCharm. Also, few times when I wasn't doing anything demanding (computation-wise) I noticed my fans working full speed. Inspecting `htop` showed that, sometimes pomatez can take quite a big chunk of processing power (the highest I saw was around 20 % of CPU).

**Comment by sekwah41** [comment] 2022-02-25 03:36
This was actually fixed a while back using #62.

By default, the smooth animations are on but the problem is that the browser seems to not have a framerate limit or something and just tries to keep updating at the maximum speed constantly.

I will leave the issue open though altering this setting should help with that.

**Comment by sekwah41** [comment] 2022-02-25 03:40
Though I may propose switching the transition off automatically as long as the time is above a certain value as it doesn't really make sense to redraw it every second when there is 20 mins or so remaining. A better solution than manually having to disable this would probably be useful.

**Comment by pared** [comment] 2022-03-17 11:38
Sorry for the late response. I can confirm that solution provided in #62 solves the problem, I think we can close it. Though if there is a plan to handle that at some point in time, I guess it doesn't hurt to leave it open.

**Comment by sekwah41** [comment] 2022-03-17 20:40
Ill close it off, it might make sense to make it so it only has the css transition if the value is below a certain size

**Closed by sekwah41** 2022-03-17 20:40 UTC
Labels: bug, duplicate
